[package]
name = "ratatui-splash-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = ">=0.25.0"
rust-embed = "8.3.0"
image = { version = "0.25.0", default-features = false, features = [
  "png",
  "jpeg",
] }

[dev-dependencies]
crossterm = "0.27.0"
anyhow = "1.0.81"
hex-literal = "0.4.1"
